name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Copy files to VM
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@172.203.225.136 "sudo rm -rf ~/app && mkdir ~/app"
        scp -r . azureuser@172.203.225.136:~/app

    - name: Install and run API on VM
      run: |
        ssh azureuser@172.203.225.136 << EOF
          cd ~/app
          sudo apt update
          sudo apt install -y nodejs npm
          npm install
          sudo fuser -k 80/tcp || true
          sudo nohup node index.js > output.log 2>&1 &
        EOF
