name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create deployment directory
      run: |
        mkdir -p deployment
        cp index.js package.json package-lock.json deployment/
        cd deployment
        
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Setup known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 172.203.225.136 >> ~/.ssh/known_hosts
        
    - name: Deploy to VM
      run: |
        # Create a deployment script
        echo '#!/bin/bash
        set -e
        
        # Create app directory if it doesn't exist
        mkdir -p ~/app
        
        # Stop existing process if running
        pm2 stop app || true
        
        # Copy files to app directory
        cp -r ./* ~/app/
        
        # Install dependencies
        cd ~/app
        npm ci --production
        
        # Start the application with PM2
        pm2 start index.js --name app || pm2 restart app
        ' > deploy.sh
        
        # Make the script executable
        chmod +x deploy.sh
        
        # Copy deployment files to VM
        scp -r deployment/* azureuser@172.203.225.136:~/
        scp deploy.sh azureuser@172.203.225.136:~/
        
        # Execute deployment script on VM
        ssh azureuser@172.203.225.136 'bash ~/deploy.sh'
